# Generated by Django 4.2.6 on 2023-12-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='vibes',
            field=models.ManyToManyField(blank=True, to='user.vibes'),
        ),
    ]
