# Generated by Django 4.2.6 on 2023-12-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('google', models.URLField()),
            ],
        ),
    ]
