# Generated by Django 4.2.6 on 2023-12-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_team_description_alter_team_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vibes',
            field=models.ManyToManyField(blank=True, related_name='vibes', to='user.vibes'),
        ),
    ]
