# Generated by Django 4.2.6 on 2023-12-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_is_online_alter_profile_vibes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(null=True),
        ),
    ]
