# Generated by Django 4.2.6 on 2023-12-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_favorite_trip_blog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
