# Generated by Django 4.2.6 on 2023-12-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_personal_favorite_trip_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='native_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
