# Generated by Django 4.2.6 on 2023-12-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_native_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onTrip',
            field=models.BooleanField(default=False),
        ),
    ]
