# Generated by Django 4.2.6 on 2024-05-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
