# Generated by Django 4.2.6 on 2024-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_newsannouncements'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsannouncements',
            name='icon',
            field=models.CharField(blank=True, default='bell', max_length=255, null=True),
        ),
    ]
