# Generated by Django 4.2.6 on 2024-05-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_newsannouncements_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplantrip',
            name='share_every_facility',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travelplantrip',
            name='share_facilities',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default=False, max_length=20, null=True),
        ),
    ]
