# Generated by Django 4.2.6 on 2024-05-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_review_user'),
        ('dashboard', '0006_alter_travelplantrip_share_every_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='vibes',
            field=models.ManyToManyField(blank=True, to='user.vibes'),
        ),
    ]
